name: nrlscriptenv
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29=py27_0
  - cffi=1.11.5=py27he75722e_1
  - intel-openmp=2019.1=144
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py27ha843d7b_0
  - mkl_random=1.0.2=py27hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py27h6bb024c_1
  - numpy=1.15.4=py27h7e9f1db_0
  - numpy-base=1.15.4=py27hde5b4d6_0
  - openssl=1.1.1a=h7b6447c_0
  - pip=19.0.1=py27_0
  - pycparser=2.19=py27_0
  - python=2.7.15=h9bab390_6
  - readline=7.0=h7b6447c_5
  - setuptools=40.7.3=py27_0
  - sqlite=3.26.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.32.3=py27_0
  - zlib=1.2.11=h7b6447c_3
  - pytorch-cpu=1.0.1=py2.7_cpu_2
  - pip:
    - boto==2.49.0
    - boto3==1.9.91
    - botocore==1.12.91
    - bz2file==0.98
    - chardet==3.0.4
    - decorator==4.3.2
    - docutils==0.14
    - futures==3.2.0
    - gensim==3.7.1
    - idna==2.8
    - jmespath==0.9.3
    - joblib==0.13.0
    - liac-arff==2.3.1
    - lockfile==0.12.2
    - networkx==2.2
    - pandas==0.22.0
    - pynisher==0.5.0
    - python-dateutil==2.8.0
    - pytz==2018.9
    - requests==2.21.0
    - s3transfer==0.2.0
    - scikit-learn==0.19.1
    - scipy==1.0.1
    - six==1.12.0
    - smart-open==1.8.0
    - torch==1.0.1.post2
    - urllib3==1.24.1
    - xgboost==0.81
prefix: /home/gurukar.1/anaconda2/envs/nrlscriptenv

